### ISSUE TITLE
Use cards for players

### ISSUE THREAD

**Issue by sidhantmishra** [mcmadbat/batter-up#20]
It would look better to have cards instead of using a table.

**Comment by mcmadbat** [comment]
this is lower priority

**Comment by smishra-toast** [comment]
Looks like this already happened, partially? Although the images aren't sized evenly for the cards if you don't have a picture for a player.

**Comment by sidhantmishra** [comment]
Looks like this has been implemented for the most part, only thing left in terms of enhancements is to make sure the icon for a player with no picture is sized the same as ones with pictures.

**Comment by mcmadbat** [comment]
I think it's safe to close
